#cloud-config

package_update: true
package_upgrade: true
packages:
  - python3.9
  - python3-pip
  - git
  - docker.io

write_files:
  - path: /etc/systemd/system/ai-app.service
    content: |
      [Unit]
      Description=AI Healthcare App
      After=network.target

      [Service]
      User=ubuntu
      WorkingDirectory=/opt/ai-app
      ExecStart=/usr/bin/python3 main.py
      Restart=always

      [Install]
      WantedBy=multi-user.target

runcmd:
  - mkdir -p /opt/ai-app
  - [git, clone, "https://github.com/shashankmsanap/Ai_app_ci_cd.git", /opt/ai-app]
  - pip3 install -r /opt/ai-app/requirements.txt
  - systemctl daemon-reload
  - systemctl enable ai-app.service
  - systemctl start ai-app.service