name: Terraform Validate
on:
  pull_request:
    paths: ['infra/**']

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"  # Pin your version

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: ./infra
        run: terraform validate -no-color

      - name: Add Validation Comment to PR
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          script: |
            const output = `Terraform validation passed!
            View details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })